In [4]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Name': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Rohit', 'Neha'],
    'Age': [22, np.nan, 24, 23, np.nan, 25],
    'City': ['Kolkata', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'Salary': [25000, 30000, np.nan, 28000, 35000, np.nan],
    'Department': ['IT', np.nan, 'HR', 'IT', 'Sales', 'HR']
}

print(data)

{'Name': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Rohit', 'Neha'], 'Age': [22, nan, 24, 23, nan, 25], 'City': ['Kolkata', 'Delhi', nan, 'Mumbai', 'Delhi', nan], 'Salary': [25000, 30000, nan, 28000, 35000, nan], 'Department': ['IT', nan, 'HR', 'IT', 'Sales', 'HR']}

In [19]:
#Display the dataset and check the missing values
df=pd.DataFrame(data)
print("DataFrame is:")
print(df)

DataFrame is:
    Name   Age     City   Salary Department
0  Rahul  22.0  Kolkata  25000.0         IT
1  Priya   NaN    Delhi  30000.0        NaN
2   Amit  24.0      NaN      NaN         HR
3  Sneha  23.0   Mumbai  28000.0         IT
4  Rohit   NaN    Delhi  35000.0      Sales
5   Neha  25.0      NaN      NaN         HR

In [20]:
print("\nMissing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Name          0
Age           2
City          2
Salary        2
Department    1
dtype: int64

In [12]:
#Check total missing values
print("\nTotal missing values:")
print(df.isnull().sum().sum())

Total missing values:
7

In [13]:
# Check whether any missing values exist
print("\nAre there any missing values?")
print(df.isnull().values.any())

Are there any missing values?
True

In [21]:
#Fill all missing values with 0 using fillna().
df.fillna(0, inplace=True)
print(df.isnull().sum())

Name          0
Age           0
City          0
Salary        0
Department    0
dtype: int64

In [26]:
#Fill missing values in the Age column with the average age.
df['Age']=df['Age'].fillna(df['Age'].mean())
print(df['Age'])

0    22.0
1     0.0
2    24.0
3    23.0
4     0.0
5    25.0
Name: Age, dtype: float64

In [31]:
#Remove all rows containing missing values using dropna().
df_drop_rows = df.dropna(inplace=True)
print("\nDrop rows with any null:\n", df_drop_rows)

Drop rows with any null:
 None

In [35]:
#Forward-fill missing values using ffill()
df.ffill()

    Name   Age     City   Salary Department
0  Rahul  22.0  Kolkata  25000.0         IT
1  Priya   0.0    Delhi  30000.0          0
2   Amit  24.0        0      0.0         HR
3  Sneha  23.0   Mumbai  28000.0         IT
4  Rohit   0.0    Delhi  35000.0      Sales
5   Neha  25.0        0      0.0         HR

In [36]:
#Backward-fill missing values using bfill().
df.bfill()

    Name   Age     City   Salary Department
0  Rahul  22.0  Kolkata  25000.0         IT
1  Priya   0.0    Delhi  30000.0          0
2   Amit  24.0        0      0.0         HR
3  Sneha  23.0   Mumbai  28000.0         IT
4  Rohit   0.0    Delhi  35000.0      Sales
5   Neha  25.0        0      0.0         HR

In [46]:
#Drop the Department column.
df_drop_col= df.drop(columns=['Department'], errors='ignore')
print(df_drop_col)

    Name   Age     City   Salary
0  Rahul  22.0  Kolkata  25000.0
1  Priya   0.0    Delhi  30000.0
2   Amit  24.0        0      0.0
3  Sneha  23.0   Mumbai  28000.0
4  Rohit   0.0    Delhi  35000.0
5   Neha  25.0        0      0.0