In [1]:
# -----------------------------------------------------------
#  Pandas: Definition, Advantages & Disadvantages
# -----------------------------------------------------------

#  Definition:
# Pandas is a fast, powerful, and flexible open-source Python library 
# used for data manipulation and analysis. 
# It provides two main data structures:
#   1. Series → 1-D labeled array
#   2. DataFrame → 2-D labeled data structure like Excel table

#  Advantages of Pandas:
# 1. Easy to use → syntax is simple and close to Excel operations
# 2. Handles missing data easily (.dropna(), .fillna())
# 3. Works well with different file formats (CSV, Excel, JSON, SQL, etc.)
# 4. Powerful data cleaning, transformation, and aggregation features
# 5. Integrated with other Python libraries like NumPy, Matplotlib, Seaborn

#  Disadvantages of Pandas:
# 1. Memory heavy for very large datasets (better to use PySpark/Dask in big data cases)
# 2. Can be slower than optimized SQL queries for large data
# 3. Not ideal for parallel/distributed computing out of the box

#  Use Cases of Pandas:
# - Data cleaning (removing nulls, duplicates)
# - Data analysis (grouping, summarization, statistics)
# - Data visualization (quick plots)
# - Input/Output with multiple formats (CSV, Excel, SQL)
# - Exploratory Data Analysis (EDA) in Data Science projects

# -----------------------------------------------------------
# 1. Importing Pandas
# -----------------------------------------------------------
# pip install pandas # if not installed
# conda install pandas # for updating
#!pip install pandas (for jupyter)
import pandas as pd  # pandas is usually imported as 'pd'
import numpy as np   # numpy is often used along with pandas
print(pd.__version__)   # shows installed version

2.2.2

In [7]:
# ----------------------------
# 2. Data Structures
# ----------------------------

# 2.1 Series
# Series is a 1-D labeled array capable of holding data of any type
# Creating a Series from a list
s = pd.Series([10, 20, 30, 40], index=['a','b','c','d'], dtype=int)  
# index is optional, dtype specifies data type

print(s)  # display the Series

# Accessing values and index
print(s.values)  # returns the numpy array of values
print(s.index)   # returns the index labels

#  Creating Series without specifying index
s = pd.Series([10, 20, 30, 40, 50])

print("Series without index:\n", s)

# Creating Series from Dictionary (without specifying index)
# -----------------------------------------------------------
data_dict = {"a": 100, "b": 200, "c": 300}
s1 = pd.Series(data_dict)

print("Series from Dictionary (default index = dictionary keys):\n", s1)


# Dictionary data
data_dict = {"a": 100, "b": 200, "c": 300}

# -----------------------------------------------------------
#  Series from Dictionary with Custom Index
# -----------------------------------------------------------
s = pd.Series(data_dict, index=["a", "b", "c", "d", "e"])  

print("Series with Custom Index:\n", s)

#  Explanation:
# - Keys 'a', 'b', 'c' matched dictionary → values assigned
# - Keys 'd' and 'e' not in dictionary → Pandas assigns NaN

a    10
b    20
c    30
d    40
dtype: int64
[10 20 30 40]
Index(['a', 'b', 'c', 'd'], dtype='object')
Series without index:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
Series from Dictionary (default index = dictionary keys):
 a    100
b    200
c    300
dtype: int64
Series with Custom Index:
 a    100.0
b    200.0
c    300.0
d      NaN
e      NaN
dtype: float64

In [7]:


# -----------------------------------------------------------
#  1. Series from List
# -----------------------------------------------------------
data_list = [10, 20, 30, 40, 50]
s_list = pd.Series(data_list)   # default index [0,1,2,3,4]
print("Series from List:\n", s_list)

#  Indexing
print("\nAccess first element (index 0):", s_list[0])     # 10
print("Access last element (index 4):", s_list[4])        # 50

#  Slicing
print("\nSlice from index 1 to 3:\n", s_list[1:4])        # elements at 1,2,3
print("Slice first three elements:\n", s_list[:3])
print("Slice from index 2 to end:\n", s_list[2:])

# -----------------------------------------------------------
#  2. Series from Dictionary
# -----------------------------------------------------------
data_dict = {"a": 100, "b": 200, "c": 300, "d": 400}
s_dict = pd.Series(data_dict)   # dictionary keys become index
print("\nSeries from Dictionary:\n", s_dict)

#  Indexing
print("\nAccess element with label 'a':", s_dict['a'])    # 100
print("Access element with label 'c':", s_dict['c'])      # 300

#  Slicing by labels (dictionary preserves insertion order in Pandas)
print("\nSlice from 'a' to 'c':\n", s_dict['a':'c'])      # includes 'a','b','c'
print("Slice from 'b' onwards:\n", s_dict['b':])          # from 'b' to end
print("Access multiple labels ['a','d']:\n", s_dict[['a','d']])  # non-continuous

Series from List:
 0    10
1    20
2    30
3    40
4    50
dtype: int64

Access first element (index 0): 10
Access last element (index 4): 50

Slice from index 1 to 3:
 1    20
2    30
3    40
dtype: int64
Slice first three elements:
 0    10
1    20
2    30
dtype: int64
Slice from index 2 to end:
 2    30
3    40
4    50
dtype: int64

Series from Dictionary:
 a    100
b    200
c    300
d    400
dtype: int64

Access element with label 'a': 100
Access element with label 'c': 300

Slice from 'a' to 'c':
 a    100
b    200
c    300
dtype: int64
Slice from 'b' onwards:
 b    200
c    300
d    400
dtype: int64
Access multiple labels ['a','d']:
 a    100
d    400
b    200
dtype: int64

In [6]:


# Single list
data = [10, 20, 30, 40, 50]

# Create DataFrame from list
df1 = pd.DataFrame(data, columns=['numbers'])  # specify column name
print(df1)

   numbers
0       10
1       20
2       30
3       40
4       50

In [7]:
# List of lists
data = [[1, 'Rohit', 25],
        [2, 'Aman', 30],
        [3, 'Neha', 22]]

# Create DataFrame
df2 = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])
print(df2)

   ID   Name  Age
0   1  Rohit   25
1   2   Aman   30
2   3   Neha   22

In [10]:
# Dictionary of lists
data_dict = {
    "ID": [1, 2, 3],
    "Name": ["Rohit", "Aman", "Neha"],
    "Age": [25, 30, 22]
}

df1 = pd.DataFrame(data_dict)
print("DataFrame from Dictionary of Lists:\n", df1)

DataFrame from Dictionary of Lists:
    ID   Name  Age
0   1  Rohit   25
1   2   Aman   30
2   3   Neha   22

In [10]:
# 2D NumPy array
data_array = np.array([[1, "Rohit", 25],
                       [2, "Aman", 30],
                       [3, "Neha", 22]])

df2 = pd.DataFrame(data_array, columns=["ID", "Name", "Age"])
print("\nDataFrame from NumPy Array:\n", df2)

DataFrame from NumPy Array:
   ID   Name Age
0  1  Rohit  25
1  2   Aman  30
2  3   Neha  22

In [12]:
# Dictionary of Pandas Series
data_series = {
    "ID": pd.Series([1, 2, 3], index=["a", "b", "c"]),
    "Name": pd.Series(["Rohit", "Aman", "Neha"], index=["a", "b", "c"]),
    "Age": pd.Series([25, 30, 22], index=["a", "b", "c"])
}

df3 = pd.DataFrame(data_series)
print("\nDataFrame from Dictionary of Series:\n", df3)

DataFrame from Dictionary of Series:
    ID   Name  Age
a   1  Rohit   25
b   2   Aman   30
c   3   Neha   22

In [5]:


# Example path (Windows)
df_csv = pd.read_csv(r"C:\Users\YourName\Documents\data.csv")

# Example path (Mac/Linux)
# df_csv = pd.read_csv("/Users/YourName/Documents/data.csv")

print(df_csv)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YourName\\Documents\\data.csv'

In [ ]:
# Windows
df_excel = pd.read_excel(r"C:\Users\YourName\Documents\data.xlsx")

# Mac/Linux
# df_excel = pd.read_excel("/Users/YourName/Documents/data.xlsx")

print(df_excel)

In [ ]:
# Windows
df_json = pd.read_json(r"C:\Users\YourName\Documents\data.json")

# Mac/Linux
# df_json = pd.read_json("/Users/YourName/Documents/data.json")

print(df_json)

In [ ]:
import sqlite3

# Connect to SQLite database
conn = sqlite3.connect(r"C:\Users\YourName\Documents\my_database.db")

# Read a table (example table = "students")
df_sql = pd.read_sql("SELECT * FROM students", conn)

print(df_sql)

# Close connection
conn.close()

In [9]:


# Read CSV file 
df = pd.read_csv(r"C:\Users\admin\Downloads\students.csv")

# Show DataFrame
print(df)

# Basic functions
print("Columns:", df.columns.tolist())     # Get column names
print("Shape:", df.shape)                  # Get number of rows & columns
print("Size:", df.size)                    # Get total number of elements
print("Index:", df.index)                  # Get row index range
print("Data Types:\n", df.dtypes)          # Get data types of each column
print("Info:\n") 
print(df.info())                           # Get summary (rows, dtypes, memory)
print("Describe:\n", df.describe())        # Summary stats for numeric columns
print("Head:\n", df.head(3))               # First 3 rows
print("Tail:\n", df.tail(2))               # Last 2 rows
print("Sample:\n", df.sample(2))           # Random 2 rows
print("Null values:\n", df.isnull().sum()) # Check missing values
print("Unique Names:", df["Name"].unique())# Unique values in Name column
print("Sorted by Age:\n", df.sort_values(by="Age",ascending=False)) # Sort by Age

   ID   Name  Age  Marks
0   1  Rohit   25     88
1   2   Aman   30     92
2   3   Neha   22     79
3   4  Priya   28     85
4   5  Karan   35     95
Columns: ['ID', 'Name', 'Age', 'Marks']
Shape: (5, 4)
Size: 20
Index: RangeIndex(start=0, stop=5, step=1)
Data Types:
 ID        int64
Name     object
Age       int64
Marks     int64
dtype: object
Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      5 non-null      int64
 1   Name    5 non-null      object
 2   Age     5 non-null      int64
 3   Marks   5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes
None
Describe:
              ID        Age      Marks
count  5.000000   5.000000   5.000000
mean   3.000000  28.000000  87.800000
std    1.581139   4.949747   6.220932
min    1.000000  22.000000  79.000000
25%    2.000000  25.000000  85.000000
50%    3.000000  28.000000  88.000000
75%    4.000000  30.000000  92.000000
max    5.000000  35.000000  95.000000
Head:
    ID   Name  Age  Marks
0   1  Rohit   25     88
1   2   Aman   30     92
2   3   Neha   22     79
Tail:
    ID   Name  Age  Marks
3   4  Priya   28     85
4   5  Karan   35     95
Sample:
    ID   Name  Age  Marks
2   3   Neha   22     79
4   5  Karan   35     95
Null values:
 ID       0
Name     0
Age      0
Marks    0
dtype: int64
Unique Names: ['Rohit' 'Aman' 'Neha' 'Priya' 'Karan']
Sorted by Age:
    ID   Name  Age  Marks
4   5  Karan   35     95
1   2   Aman   30     92
3   4  Priya   28     85
0   1  Rohit   25     88
2   3   Neha   22     79

In [17]:


# Creating a DataFrame with some null values
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Rohit", "Aman", None, "Priya", "Karan"],
    "Age": [25, None, 22, 28, None],
    "Marks": [88, 92, np.nan, 85, 95]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

Original DataFrame:
    ID   Name   Age  Marks
0   1  Rohit  25.0   88.0
1   2   Aman   NaN   92.0
2   3   None  22.0    NaN
3   4  Priya  28.0   85.0
4   5  Karan   NaN   95.0

In [18]:
# Check null values in entire DataFrame (True means Null)
print("\nCheck null values:\n", df.isnull())

# Count null values in each column
print("\nCount of null values in each column:\n", df.isnull().sum())

Check null values:
       ID   Name    Age  Marks
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False  False   True  False

Count of null values in each column:
 ID       0
Name     1
Age      2
Marks    1
dtype: int64

In [19]:
#df_drop_rows = df.dropna()  # removes all rows containing at least one null
#print("\nDrop rows with any null:\n", df_drop_rows)

In [ ]:
#df_drop_cols = df.dropna(axis=1)  # removes columns with any null
#print("\nDrop columns with any null:\n", df_drop_cols)

In [ ]:
#df_drop_all = df.dropna(how="all"),df.dropna(inplace=True)
#print("\nDrop rows where all values are null:\n", df_drop_all)

In [ ]:
#df_drop_age = df.dropna(subset=["Age"])
#print("\nDrop rows where Age is null:\n", df_drop_age)

In [ ]:
#df_fill_const = df.fillna(0)  # replace all nulls with 0
#print("\nFill all null values with 0:\n", df_fill_const)

In [20]:
#df_fill_cols = df.fillna({"Name": "Unknown", "Age": 0, "Marks": df["Marks"].mean()})
#print("\nFill column-wise:\n", df_fill_cols)

In [ ]:
#df_ffill = df.fillna(method="ffill")
#print("\nForward fill:\n", df_ffill)

In [ ]:
#df_bfill = df.fillna(method="bfill")
#print("\nBackward fill:\n", df_bfill)

In [ ]:
# Replace nulls in Age with 0 directly in df
#df.fillna({"Age": 0}, inplace=True)

#print("\nAfter inplace fill for Age:\n", df)

In [4]:

data = {
    "ID": [1, 2, 3, 4, 5],
    "Age": [25, None, 22, None, 30],
    "Marks": [88, None, 79, None, 95]
}
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Forward Fill
df_ffill = df.fillna(method="ffill")
print("\nAfter Forward Fill (ffill):\n", df_ffill)

# Backward Fill
df_bfill = df.fillna(method="bfill")
print("\nAfter Backward Fill (bfill):\n", df_bfill)

     name      sal loan
0   rohit  60000.0  yes
1  puspak      NaN   no
Original DataFrame:
    ID   Age  Marks
0   1  25.0   88.0
1   2   NaN    NaN
2   3  22.0   79.0
3   4   NaN    NaN
4   5  30.0   95.0

After Forward Fill (ffill):
    ID   Age  Marks
0   1  25.0   88.0
1   2  25.0   88.0
2   3  22.0   79.0
3   4  22.0   79.0
4   5  30.0   95.0

After Backward Fill (bfill):
    ID   Age  Marks
0   1  25.0   88.0
1   2  22.0   79.0
2   3  22.0   79.0
3   4  30.0   95.0
4   5  30.0   95.0

C:\Users\admin\AppData\Local\Temp\ipykernel_16436\1027835343.py:17: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method="ffill")
C:\Users\admin\AppData\Local\Temp\ipykernel_16436\1027835343.py:21: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method="bfill")

In [22]:
#DataFrame.replace(to_replace, value, inplace=False, regex=False)


# Example DataFrame of students
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Rohit", "Ankit", "Unknown", "Priya", "Unknown"],
    "Subject": ["Math", "English", "Math", "Science", "Math"],
    "Marks": [88, -1, 79, -1, 95]
}
df = pd.DataFrame(data)

print(" Original DataFrame:\n", df)
#syntax=df.replace(old_value,new_value)
# 1. Replace a single value
# Here we replace -1 with 0 in Marks column
df1 = df.replace(-1, 0)
print("\n Replace -1 with 0:\n", df1)

# 2. Replace multiple values with one value
# Replace 'Unknown' names with 'Not Available'
df2 = df.replace("Unknown", "Not Available")
print("\n Replace 'Unknown' with 'Not Available':\n", df2)

# 3. Replace multiple values with multiple new values (using dict)
# Here -1 → 50, 'Unknown' → 'NA'
df3 = df.replace({-1: 50, "Unknown": "NA"})
print("\n Replace multiple values using dictionary:\n", df3)

# 4. Replace using regex (all names starting with 'P' → 'Name Hidden')
df4 = df.replace(to_replace=r"^P.*", value="Name Hidden", regex=True)
print("\n Replace using regex:\n", df4)
#df["Name"].replace(r"Mr\.","",regex=True)
# 5. Inplace replacement (modifies the original DataFrame directly)
df.replace(-1, 0, inplace=True)
print("\n Original DataFrame after inplace replacement:\n", df)

 Original DataFrame:
    ID     Name  Subject  Marks
0   1    Rohit     Math     88
1   2    Ankit  English     -1
2   3  Unknown     Math     79
3   4    Priya  Science     -1
4   5  Unknown     Math     95

 Replace -1 with 0:
    ID     Name  Subject  Marks
0   1    Rohit     Math     88
1   2    Ankit  English      0
2   3  Unknown     Math     79
3   4    Priya  Science      0
4   5  Unknown     Math     95

 Replace 'Unknown' with 'Not Available':
    ID           Name  Subject  Marks
0   1          Rohit     Math     88
1   2          Ankit  English     -1
2   3  Not Available     Math     79
3   4          Priya  Science     -1
4   5  Not Available     Math     95

 Replace multiple values using dictionary:
    ID   Name  Subject  Marks
0   1  Rohit     Math     88
1   2  Ankit  English     50
2   3     NA     Math     79
3   4  Priya  Science     50
4   5     NA     Math     95

 Replace using regex:
    ID         Name  Subject  Marks
0   1        Rohit     Math     88
1   2        Ankit  English     -1
2   3      Unknown     Math     79
3   4  Name Hidden  Science     -1
4   5      Unknown     Math     95

 Original DataFrame after inplace replacement:
    ID     Name  Subject  Marks
0   1    Rohit     Math     88
1   2    Ankit  English      0
2   3  Unknown     Math     79
3   4    Priya  Science      0
4   5  Unknown     Math     95

In [23]:


# Sample DataFrame with messy data
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Rohit123", "Ankit_99", "Priya!!!", "Pooja#", "Ramesh_45"],
    "Email": ["rohit@mail.com", "ankit@gmail", "priya@xyz.com", "pooja@", "123@abc.com"],
    "Phone": ["+91-9876543210", "98765 43210", "91-9876543210", "0000000000", "987654321"]
}
df = pd.DataFrame(data)

print(" Original DataFrame:\n", df)

# 1. Remove all numbers from Name column
df1 = df.copy()
df1["Name"] = df1["Name"].replace(to_replace=r"[0-9]", value="", regex=True)
print("\n Removed all numbers from Name column:\n", df1)

# 2. Remove all special characters from Name column
df2 = df.copy()
df2["Name"] = df2["Name"].replace(to_replace=r"[^a-zA-Z]", value="", regex=True)
print("\n Removed all special characters, kept only alphabets in Name:\n", df2)

# 3. Keep only valid email addresses (must contain @ and .)
'''df3 = df.copy()
df3["Email"] = df3["Email"].replace(to_replace=r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$", value="Invalid Email", regex=True)
print("\n Mark invalid emails:\n", df3)'''

# 4. Standardize phone numbers (keep only digits)
df4 = df.copy()
df4["Phone"] = df4["Phone"].replace(to_replace=r"[^0-9]", value="", regex=True)
print("\n Phone numbers with only digits:\n", df4)

# 5. Mask sensitive phone numbers (show only last 4 digits)
df5 = df4.copy()
df5["Phone"] = df5["Phone"].replace(to_replace=r"[0-9]{6}", value="XXXXXX", regex=True)
print("\n Masked phone numbers (only last 4 visible):\n", df5)

 Original DataFrame:
    ID       Name           Email           Phone
0   1   Rohit123  rohit@mail.com  +91-9876543210
1   2   Ankit_99     ankit@gmail     98765 43210
2   3   Priya!!!   priya@xyz.com   91-9876543210
3   4     Pooja#          pooja@      0000000000
4   5  Ramesh_45     123@abc.com       987654321

 Removed all numbers from Name column:
    ID      Name           Email           Phone
0   1     Rohit  rohit@mail.com  +91-9876543210
1   2    Ankit_     ankit@gmail     98765 43210
2   3  Priya!!!   priya@xyz.com   91-9876543210
3   4    Pooja#          pooja@      0000000000
4   5   Ramesh_     123@abc.com       987654321

 Removed all special characters, kept only alphabets in Name:
    ID    Name           Email           Phone
0   1   Rohit  rohit@mail.com  +91-9876543210
1   2   Ankit     ankit@gmail     98765 43210
2   3   Priya   priya@xyz.com   91-9876543210
3   4   Pooja          pooja@      0000000000
4   5  Ramesh     123@abc.com       987654321

 Mark invalid emails:
    ID       Name           Email           Phone
0   1   Rohit123  rohit@mail.com  +91-9876543210
1   2   Ankit_99     ankit@gmail     98765 43210
2   3   Priya!!!   priya@xyz.com   91-9876543210
3   4     Pooja#          pooja@      0000000000
4   5  Ramesh_45     123@abc.com       987654321

 Phone numbers with only digits:
    ID       Name           Email         Phone
0   1   Rohit123  rohit@mail.com  919876543210
1   2   Ankit_99     ankit@gmail    9876543210
2   3   Priya!!!   priya@xyz.com  919876543210
3   4     Pooja#          pooja@    0000000000
4   5  Ramesh_45     123@abc.com     987654321

 Masked phone numbers (only last 4 visible):
    ID       Name           Email         Phone
0   1   Rohit123  rohit@mail.com  XXXXXXXXXXXX
1   2   Ankit_99     ankit@gmail    XXXXXX3210
2   3   Priya!!!   priya@xyz.com  XXXXXXXXXXXX
3   4     Pooja#          pooja@    XXXXXX0000
4   5  Ramesh_45     123@abc.com     XXXXXX321

In [2]:
#.loc takes name
#.iloc takes position

# Sample DataFrame
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Rohit", "Aman", "Neha", "Priya", "Karan"],
    "Age": [25, 30, 22, 28, 35],
    "Marks": [88, 92, 79, 85, 95]
}
df = pd.DataFrame(data, index=["a", "b", "c", "d", "e"])  # custom row labels

print(" Original DataFrame:\n", df)

# -------------------- LOC Examples --------------------

# 1. Select row with label 'b'
print("\n.loc['b'] → Select row with label 'b':\n", df.loc["b"])

# 2. Select multiple rows by label
print("\n.loc[['a','c','e']] → Select multiple rows by label:\n", df.loc[["a", "c", "e"]])

# 3. Select rows from 'a' to 'c' (inclusive)
print("\n.loc['a':'c'] → Range selection by label:\n", df.loc["a":"c"])

# 4. Select specific rows and specific columns
print("\n.loc[['a','c'], ['Name','Marks']] → Specific rows and columns:\n", df.loc[["a","c"], ["Name","Marks"]])


# -------------------- ILOC Examples --------------------

# 1. Select first row (position 0)
print("\n.iloc[0] → Select first row by position:\n", df.iloc[0])

# 2. Select first three rows
print("\n.iloc[0:3] → First three rows (end not included):\n", df.iloc[0:3])

# 3. Select specific rows and columns by number
print("\n.iloc[[0,2], [1,3]] → Select row 0 and 2, column 1 and 3:\n", df.iloc[[0,2], [1,3]])

# 4. Select last row
print("\n.iloc[-1] → Last row:\n", df.iloc[-1])

 Original DataFrame:
    ID   Name  Age  Marks
a   1  Rohit   25     88
b   2   Aman   30     92
c   3   Neha   22     79
d   4  Priya   28     85
e   5  Karan   35     95

.loc['b'] → Select row with label 'b':
 ID          2
Name     Aman
Age        30
Marks      92
Name: b, dtype: object

.loc[['a','c','e']] → Select multiple rows by label:
    ID   Name  Age  Marks
a   1  Rohit   25     88
c   3   Neha   22     79
e   5  Karan   35     95

.loc['a':'c'] → Range selection by label:
    ID   Name  Age  Marks
a   1  Rohit   25     88
b   2   Aman   30     92
c   3   Neha   22     79
d   4  Priya   28     85
e   5  Karan   35     95

.loc[['a','c'], ['Name','Marks']] → Specific rows and columns:
     Name  Marks
a  Rohit     88
c   Neha     79

.iloc[0] → Select first row by position:
 ID           1
Name     Rohit
Age         25
Marks       88
Name: a, dtype: object

.iloc[0:3] → First three rows (end not included):
    ID   Name  Age  Marks
a   1  Rohit   25     88
b   2   Aman   30     92
c   3   Neha   22     79

.iloc[[0,2], [1,3]] → Select row 0 and 2, column 1 and 3:
     Name  Marks
a  Rohit     88
c   Neha     79

.iloc[-1] → Last row:
 ID           5
Name     Karan
Age         35
Marks       95
Name: e, dtype: object

In [25]:


# Sample employee data
data = {
    "Employee": ["Rohit", "Aman", "Neha", "Priya", "Karan", "Anita"],
    "Department": ["IT", "HR", "IT", "Finance", "Finance", "HR"],
    "Salary": [50000, 45000, 52000, 60000, 58000, 47000]
}
df = pd.DataFrame(data)
print(" Original DataFrame:\n", df)

# Group by Department and calculate average salary
grouped = df.groupby("Department")["Salary"].mean()
print("\n Average Salary by Department:\n", grouped)

# Group by Department and show multiple aggregations
multi_group = df.groupby("Department")["Salary"].agg(["sum", "mean", "max", "min"])
print("\n Multiple aggregations on Salary:\n", multi_group)

 Original DataFrame:
   Employee Department  Salary
0    Rohit         IT   50000
1     Aman         HR   45000
2     Neha         IT   52000
3    Priya    Finance   60000
4    Karan    Finance   58000
5    Anita         HR   47000

 Average Salary by Department:
 Department
Finance    59000.0
HR         46000.0
IT         51000.0
Name: Salary, dtype: float64

 Multiple aggregations on Salary:
                sum     mean    max    min
Department
Finance     118000  59000.0  60000  58000
HR           92000  46000.0  47000  45000
IT          102000  51000.0  52000  50000

In [26]:
# Employee table
employees = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["Rohit", "Aman", "Neha", "Priya"],
    "DeptID": [101, 102, 101, 103]
})

# Department table
departments = pd.DataFrame({
    "DeptID": [101, 102, 103, 104],
    "Department": ["IT", "HR", "Finance", "Admin"]
})

print("\n Employees Table:\n", employees)
print("\n Departments Table:\n", departments)

# Merge on DeptID (like SQL JOIN)
merged_inner = pd.merge(employees, departments, on="DeptID", how="inner")
print("\n Inner Join (common values only):\n", merged_inner)

merged_left = pd.merge(employees, departments, on="DeptID", how="left")
print("\n Left Join (all employees, matching dept if available):\n", merged_left)

merged_outer = pd.merge(employees, departments, on="DeptID", how="outer")
print("\n Outer Join (all data from both tables):\n", merged_outer)

 Employees Table:
    EmpID   Name  DeptID
0      1  Rohit     101
1      2   Aman     102
2      3   Neha     101
3      4  Priya     103

 Departments Table:
    DeptID Department
0     101         IT
1     102         HR
2     103    Finance
3     104      Admin

 Inner Join (common values only):
    EmpID   Name  DeptID Department
0      1  Rohit     101         IT
1      2   Aman     102         HR
2      3   Neha     101         IT
3      4  Priya     103    Finance

 Left Join (all employees, matching dept if available):
    EmpID   Name  DeptID Department
0      1  Rohit     101         IT
1      2   Aman     102         HR
2      3   Neha     101         IT
3      4  Priya     103    Finance

 Outer Join (all data from both tables):
    EmpID   Name  DeptID Department
0    1.0  Rohit     101         IT
1    3.0   Neha     101         IT
2    2.0   Aman     102         HR
3    4.0  Priya     103    Finance
4    NaN    NaN     104      Admin

In [4]:


# First DataFrame
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Rohit", "Aman", "Neha"]
})

# Second DataFrame
df2 = pd.DataFrame({
    "ID": [4, 5],
    "Name": ["Priya", "Karan"]
})

print(" First DataFrame:\n", df1)
print("\n Second DataFrame:\n", df2)

# Concatenate df1 and df2 (instead of append)
df_concat = pd.concat([df1, df2], ignore_index=True)
print("\n After Concatenation:\n", df_concat)

 First DataFrame:
    ID   Name
0   1  Rohit
1   2   Aman
2   3   Neha

 Second DataFrame:
    ID   Name
0   4  Priya
1   5  Karan

 After Concatenation:
    ID   Name
0   1  Rohit
1   2   Aman
2   3   Neha
3   4  Priya
4   5  Karan

In [31]:
#df.pivot_table(values, index, columns, aggfunc)


# Sample employee data
data = {
    "Employee": ["Rohit", "Aman", "Neha", "Priya", "Karan", "Anita"],
    "Department": ["IT", "HR", "IT", "Finance", "Finance", "HR"],
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female"],
    "Salary": [50000, 45000, 52000, 60000, 58000, 47000]
}

df = pd.DataFrame(data)
print(" Original DataFrame:\n", df)

# Pivot table: Average salary by Department
pivot1 = pd.pivot_table(df, values="Salary", index="Department", aggfunc="mean")
print("\n Average Salary by Department:\n", pivot1)

# Pivot table: Average salary by Department and Gender
pivot2 = pd.pivot_table(df, values="Salary", index="Department", columns="Gender", aggfunc="mean")
print("\n Average Salary by Department and Gender:\n", pivot2)

# Pivot table: Multiple aggregations
pivot3 = pd.pivot_table(df, values="Salary", index="Department", aggfunc=["mean", "sum", "max", "min"])
print("\n Multiple Aggregations on Salary:\n", pivot3)

 Original DataFrame:
   Employee Department  Gender  Salary
0    Rohit         IT    Male   50000
1     Aman         HR    Male   45000
2     Neha         IT  Female   52000
3    Priya    Finance  Female   60000
4    Karan    Finance    Male   58000
5    Anita         HR  Female   47000

 Average Salary by Department:
              Salary
Department
Finance     59000.0
HR          46000.0
IT          51000.0

 Average Salary by Department and Gender:
 Gender       Female     Male
Department
Finance     60000.0  58000.0
HR          47000.0  45000.0
IT          52000.0  50000.0

 Multiple Aggregations on Salary:
                mean     sum    max    min
             Salary  Salary Salary Salary
Department
Finance     59000.0  118000  60000  58000
HR          46000.0   92000  47000  45000
IT          51000.0  102000  52000  50000

In [2]:


data = pd.DataFrame({
    'A':[10, 20, 30],
    'B':[1, 2, 3]
})

# Addition
data['C'] = data['A'] + data['B']

# Subtraction
data['D'] = data['A'] - data['B']

# Multiplication
data['E'] = data['A'] * data['B']

# Division
data['F'] = data['A'] / data['B']
print(data)

    A  B   C   D   E     F
0  10  1  11   9  10  10.0
1  20  2  22  18  40  10.0
2  30  3  33  27  90  10.0

In [3]:
# Mean, Sum, Max, Min
print(data['A'].mean())  # average
print(data['B'].sum())   # sum
print(data['A'].max())   # maximum
print(data['B'].min())   # minimum

20.0
6
30
1

In [5]:
data = pd.DataFrame({
    'Department':['HR', 'IT', 'HR', 'IT', 'Sales'],
    'Employee':['A','B','C','D','E'],
    'Salary':[50000,60000,52000,61000,45000]
})

# Group by Department and get sum of Salary
grouped = data.groupby('Department')['Salary'].sum()
print(grouped)

Department
HR       102000
IT       121000
Sales     45000
Name: Salary, dtype: int64

In [6]:
grouped = data.groupby('Department')['Salary'].agg(['mean','max','min'])
print(grouped)

               mean    max    min
Department
HR          51000.0  52000  50000
IT          60500.0  61000  60000
Sales       45000.0  45000  45000

In [5]:
import pandas as pd

data = {10, 20, 30, 40}
s = pd.Series(list(data))

print(s)

0    40
1    10
2    20
3    30
dtype: int64

In [1]:
import pandas as pd

# Create DataFrame
data = {
    "Name": ["Amit", "Rohit", "Priya", "Neha", "Arjun"],
    "Age": [23, 25, 22, 24, 26],
    "Marks": [85, 90, 88, 92, 87]
}

df = pd.DataFrame(data)

print("Original DataFrame:\n")
print(df)

Original DataFrame:

    Name  Age  Marks
0   Amit   23     85
1  Rohit   25     90
2  Priya   22     88
3   Neha   24     92
4  Arjun   26     87

In [2]:
print("\n3rd Row:\n")
print(df.iloc[2])

3rd Row:

Name     Priya
Age         22
Marks       88
Name: 2, dtype: object

In [3]:
print("\n3rd Row and 2nd Column:\n")
print(df.iloc[2, 1])

3rd Row and 2nd Column:

22

In [4]:
print("\nFirst 4 rows and first 2 columns:\n")
print(df.iloc[:4, :2])

First 4 rows and first 2 columns:

    Name  Age
0   Amit   23
1  Rohit   25
2  Priya   22
3   Neha   24

In [3]:
data={
    "dept":["HR","IT","HR","IT","Finance"],
    "sal":[50000,70000,60000,80000,90000]
}
df= pd.DataFrame(data)
print(df)

      dept    sal
0       HR  50000
1       IT  70000
2       HR  60000
3       IT  80000
4  Finance  90000

In [8]:
df.groupby("dept")["sal"].agg(["sum","mean","max","min"])

            sum     mean    max    min
dept
Finance   90000  90000.0  90000  90000
HR       110000  55000.0  60000  50000
IT       150000  75000.0  80000  70000

In [10]:
df=pd.read_csv(r"C:\Users\admin\Downloads\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [11]:
group_by_frame=df.groupby('Base Flavor')

In [13]:
group_by_frame[["Flavor Rating","Texture Rating"]].mean()

             Flavor Rating  Texture Rating
Base Flavor
Chocolate              8.4        7.233333
Vanilla                5.7        5.650000