In [3]:
#Module, package, Library
#Module - A single .py file ccontaining exucutable code, functions, classes
#package - A folder containing modules and an __init__.py file.
#Library - The library is having a collection of related functionality of codes that allows us to perform many tasks without writing code.
#Numpy - Numerical Python
#To use numpy we need to import tha numpy library
import numpy as np

#Creating an array      Syntax     arr_variable=np.array(list_variable)
#1D array

lst_1=[1,2,3,4,5]
arr_1=np.array(lst_1)
print(arr_1)

[1 2 3 4 5]

In [4]:
#2D Array
lst_2=[[1,2,3],[3,4,5],[5,6,7]]
arr_2=np.array(lst_2)
print(arr_2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]

In [5]:
#3D array
lst_3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr_3=np.array(lst_3)
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

In [6]:
#Dimension       arr_variable.ndim
#shape           arr_variable.shape
#size            arr_variable.size
print(arr_3.ndim)

print(arr_3.shape)

print(arr_3.size)

3
(2, 2, 3)
12

In [7]:
#np.zeros((shape)) - It creates an array of elements having value 0
arr_zero=np.zeros((2,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]

In [8]:
#np.ones((shape)) - It creates an array of the given shape where all elements are one
arr_ones=np.ones((3,3))

In [9]:
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [10]:
#np.full((shape),value) - It creates an array of the given shape where each elememts are same as the given value
arr_full=np.full((2,3),9)
print(arr_full)

[[9 9 9]
 [9 9 9]]

In [11]:
#np.eye(row_number) - It creates an array which is like Identity matrix
arr_identity=np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [12]:
#np.random.rand(shape) - It creates an array of random numbers between 0 and 1 of the given shape
arr_random=np.random.rand(2,3)
print(arr_random)

[[0.51698568 0.30176924 0.26876104]
 [0.84745242 0.80468672 0.15986205]]

In [13]:
#np.arange(start,stop,step_size) - This is similar with the range function in the loop
arr_range=np.arange(1,10,2)
print(arr_range)

[1 3 5 7 9]

In [14]:
#Mathematical operation on array - element wise mathematical operation
arr_1=np.array([[1,2,3],[4,5,6]])
print(arr_1)
print("---------------")
arr_2=np.array([[7,8,9],[10,11,12]])
print(arr_2)

[[1 2 3]
 [4 5 6]]
---------------
[[ 7  8  9]
 [10 11 12]]

In [15]:
arr_add=arr_1+arr_2
print(arr_add)

[[ 8 10 12]
 [14 16 18]]

In [16]:
arr_1*arr_2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [17]:
lst_4=[2,3,4,7,8,9]
lst_5=[]
for i in lst_4:

  lst_5.append(i**2)
print(lst_5)

[4, 9, 16, 49, 64, 81]

In [18]:
arr_6=np.array(lst_4)
arr_6**2

array([ 4,  9, 16, 49, 64, 81])

In [19]:
#Reshape any array - Syntax
#Array_variable.reshape(shape)

print(arr_add)

print("--- Array after reshape ------")

print(arr_add.reshape(3,2))

[[ 8 10 12]
 [14 16 18]]
--- Array after reshape ------
[[ 8 10]
 [12 14]
 [16 18]]

In [20]:
#Flatten - It flats any dimesion array to 1D array
#Syntax     array_variable.flatten()

print(arr_3)

print("--- Array after flat operation ---")

print(arr_3.flatten())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--- Array after flat operation ---
[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [21]:
#Array indexing and slicing
arr_8=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(arr_8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

In [22]:
#Accessing any element from an array
#Syntax    arr_variable[row_index_no,column_index_no]
print(arr_8[1,2])

8

In [23]:
arr_8[3,3]

np.int64(19)

In [24]:
#Slicing of array
#Syntax       array_variable[row_slicing,column_slicing]
arr_8[0:2,1:3] #row having index number 0 and 1 while column having index number1 and 2

array([[2, 3],
       [7, 8]])

In [25]:
#Broadcasting - It helps in the element wise operation between two arrays having different shape
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

In [26]:
vector=np.array([10,20,30])
print(vector)
print(vector.shape)

[10 20 30]
(3,)

In [27]:
arr_9=matrix+vector

In [28]:
arr_9

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [29]:
#Pandas - pandas library is used for data manipulation and data analysis
#It gives two types of data structure - Series(1D) and Data Frame(2D)
#In our tabular data structure single column is known as series and multiple columns form the Data Frame
#So to use pandas library we need to import it
#Creating the data farme

import pandas as pd

#Method-1(Dictionary of list)

emp_details={"Emp_id":[101,102,103,104,105],
             "Emp_name":["Rahul","Sanjib","Rohit","Mukul","Riya"],
             "Address":["Kolkata","Siliguri","Kanpur","Patna","Bhubaneswar"],
             "Department":["Data Analysis","Management","Data Analysis","Data Science","Sales"]}
emp_details

{'Emp_id': [101, 102, 103, 104, 105],
 'Emp_name': ['Rahul', 'Sanjib', 'Rohit', 'Mukul', 'Riya'],
 'Address': ['Kolkata', 'Siliguri', 'Kanpur', 'Patna', 'Bhubaneswar'],
 'Department': ['Data Analysis',
  'Management',
  'Data Analysis',
  'Data Science',
  'Sales']}

In [30]:
#Convert the above to Data Frame
emp_info=pd.DataFrame(emp_details)
print(emp_info)

   Emp_id Emp_name      Address     Department
0     101    Rahul      Kolkata  Data Analysis
1     102   Sanjib     Siliguri     Management
2     103    Rohit       Kanpur  Data Analysis
3     104    Mukul        Patna   Data Science
4     105     Riya  Bhubaneswar          Sales

In [31]:
#method-2(List of dictionary)
world_leader=[{"country":"USA","Leader":"Donald Trump","Designation":"President"},
              {"country":"China","Leader":"Xi Xinping","Designation":"President"},
              {"country":"Russia","Leader":"Vladimir Putin","Designation":"President"},
              {"country":"India","Leader":"Narendra Modi","Designation":"Prime Minister"}]
world_leader

[{'country': 'USA', 'Leader': 'Donald Trump', 'Designation': 'President'},
 {'country': 'China', 'Leader': 'Xi Xinping', 'Designation': 'President'},
 {'country': 'Russia', 'Leader': 'Vladimir Putin', 'Designation': 'President'},
 {'country': 'India',
  'Leader': 'Narendra Modi',
  'Designation': 'Prime Minister'}]

In [32]:
leaders=pd.DataFrame(world_leader)
leaders

  country          Leader     Designation
0     USA    Donald Trump       President
1   China      Xi Xinping       President
2  Russia  Vladimir Putin       President
3   India   Narendra Modi  Prime Minister

In [33]:
#Reading the file
#Syntax  - pd.read_excel("file_path"), pd.read_csv("file_path"),pd.read_json("file_path"),pd.read_html("file_path"),pd.read_sql("file_path")
import pandas as pd

flight= pd.read_excel("/Users/cashify/Desktop/Rahul’s MacBook/Personal Stuffs/Certification In Generative AI /Dataset(Python)/flight_price (1).xlsx")
flight

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [34]:
google=pd.read_csv("/content/googleplaystore.csv")
google

FileNotFoundError: [Errno 2] No such file or directory: '/content/googleplaystore.csv'

In [ ]:
#Data Inspection
#syntax     dataframe.head()    Top 5 data
flight.head()

In [ ]:
#Top n data
#syntax   dataframe.head(n)
flight.head(50)

In [ ]:
#Bottom data
#Bottom 5 data
#Syntax       dataframe.tail()
flight.tail()

In [ ]:
#Bottom  n data
#Syntax       dataframe.tail(n)
flight.tail(10)

In [ ]:
#To check the random data
#syntax     Dataframe.sample()
flight.sample()

In [ ]:
#Random n data
#Syntax      Dataframe.sample(n)
flight.sample(5)

In [ ]:
#To check tha shape of the data
#Syntax      Dataframe.shape()
flight.shape

In [ ]:
#To get the list of all the columns from the dataset
#Syntax    Dataframe.columns()
flight.columns.to_list()

In [ ]:
#To check the null values
#Syntax     dataframe.isnull().sum()
flight.isnull().sum()

In [ ]:
#Percentage of null value
#Syntax     (DataFrame.isnull().sum()/len(DataFrame))*100
(google.isnull().sum()/len(google))*100

In [ ]:
#To get the data types of any column
#Syntax     DataFrame.dtypes
flight.dtypes

In [ ]:
#To get both non-null values as well as the data types of the columns
#Syntax     DataFrame.info()
flight.info()

In [ ]:
#To get the basic statistical information - Only for numerical column
#Syntax      DataFrame.describe()
flight.describe()

In [ ]:
google.describe().transpose()

In [ ]:
#How to handle null values
#If in any column the percentage null value is in the range of 2-4% then drop all the null values
#Then if we do not want to drop the null values then we can impute the null values
#To impute the null values in any numerical columns we can take the mean,median or any default values
#To impute the null values in categorical columns we can use the mode of the column

#To drop the null values from the whole data set
#Syntax     DataFrame.dropna()
flight.dropna(inplace=True)   #inplace=True  it means make the same changes in the entire data set

In [ ]:
flight.isnull().sum()

In [ ]:
google.columns

In [ ]:
#filter the data only on the basis of column
#Syntax     Dataframe["col_name"]   to filter single column
#Syntax     DataFrame[["col_1","col_2","col_3"...]]
google["App"].head()

In [ ]:
google_sub=google[["App","Category","Rating","Price","Android Ver"]]
google_sub.head()

In [ ]:
(google.isnull().sum()/len(google))*100

In [ ]:
google.head()

In [ ]:
#Dropping null values from the specific columns and it creats a new Dta frame
google[["Type","Content Rating","Current Ver","Android Ver"]].dropna(inplace=True)   #It creates a new DataFrame

In [ ]:
google["Rating"].median()

In [ ]:
#Impute the null values instead of dropping it
#Syntax          Dataframe["column"].fillna(Value,inplace=True)
#Impute null value with a default value      Dataframe["Col"].fillna(default_value,inpace=True)
#Impute null value with a mean value of the column      Dataframe["Col"].fillna(dataframe["col"].mean(),inpace=True)
#Impute null value with a median value of the column      Dataframe["Col"].fillna(dataframe["col"].median(),inpace=True)
#Impute null value with a mode value of the column      Dataframe["Col"].fillna(dataframe["col"].mode(),inpace=True)


#Impute the null values of rating column from it's mean value

google["Rating"].fillna(google["Rating"].mean(),inplace=True)

In [ ]:
google.isnull().sum()

In [ ]:
#Dropping all the null values at a time
google.dropna(inplace=True)

In [ ]:
google.isnull().sum()

In [ ]:
#To check the duplicate rows
#Syntax      Dataframe.duplicated().sum()
google.duplicated().sum()

In [ ]:
#Dropping the duplicated rows
#Syntax      Dataframe.drop_duplicates(inplace=True)
google.drop_duplicates(inplace=True)

In [ ]:
google.duplicated().sum()

In [ ]:
#To get the unique data in a column
#Syntax     DataFrame["col"].unique()
google["Category"].unique()

In [ ]:
#To get the count of unique values
#Syntax     DataFrame["col"].nunique()
google["Category"].nunique()

In [ ]:
google.shape

In [ ]:
#Count of data from each category
#Syntax        Dataframe["col"].value_counts()
google["Category"].value_counts().sort_values(ascending=False)

In [ ]:
google

In [ ]:
#Accessing both rows and columns together
#loc() method
#Syntax      Dataframe.loc[row_slicing,["col_1","col_2","col_3","col_4"...]]
#Row_slicing=[start:end:step_size]
google.loc[0:10:2,["App","Category","Rating"]]

In [ ]:
#iloc() method
#Syntax       DataFrame.iloc[row_slicing,column_slicing]
google.iloc[0:10,0:5]

In [ ]:
#How can we change the Data Type of any column in thye DataFrame
#Manual Conversion type
#Changing the data type of one column at a time
#syntax       Dataframe["col"]= Dataframe["col"].astype("int/float/string/datetime64[ns]")

#Changing the data type of multiple columns at a time
#Syntax       dataframe.astype({"col_1":"int","col_2":"float"...})

#We can take the help of some specialized helper function
#pd.to_numeric(dataframe["column"])        pd.to_datetime()

#Syntax       Dataframe["Col"]=pd.to_datetime(Dataframe["Col"],format="%d %m %Y")
flight["Date_of_Journey"]=pd.to_datetime(flight["Date_of_Journey"])
flight["Date_of_Journey"]

In [ ]:
#Extracting Day, month, year from the given datetime
#df["Year"]=df["Date_of_Journey"].dt.year
flight["Month"]=flight["Date_of_Journey"].dt.month
flight["Day"]=flight["Date_of_Journey"].dt.day

In [ ]:
flight.head()

In [ ]:
#Group By
#Syntax       Dataframe.groupby("col")["Numerical_column"].aggregate_function()
flight.groupby("Airline")["Price"].sum().sort_values(ascending=False)

In [ ]:
flight.groupby(["Airline","Source"])["Price"].sum()

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [14, 28, 45, 72]}
df2 = pd.DataFrame(data)
df2

In [ ]:
#apply() - it helps us to apply udf to the Dataframe
#Syntax       DataFrame["New_col"]=DataFrame["Existing_col"].apply("udf_name")
def categorizer(age):
  if age<=18:
    return "Teen"
  elif age>18 and age<=35:
    return "Young Age"
  elif age>35 and age<=55:
    return "Middle Age"
  else:
    return "Old Age"

In [ ]:
df2["Age_category"]=df2["Age"].apply(categorizer)
df2